### ISSUE TITLE
Schematics in pdf

### ISSUE THREAD

**Issue by piotrva** [octosavvi/ESPKey#1]
Please add schematics in pdf or other universal format - now in order to view the schematic you need to download KiCad...

**Comment by Dan-Rdd** [comment]
Use EasyEDA you can import the kicad design and get everything :)

**Comment by Dan-Rdd** [comment]
> Please add schematics in pdf or other universal format - now in order to view the schematic you need to download KiCad...

Use EasyEDA you can import the kicad design and get everything :)

**Comment by piotrva** [comment]
Well, still it requires you to download it, and do some operations - nearly all other hardware I see on github has a pdf or graphic format of schematic.

**Comment by piotrva** [comment]
Also it requires the user to register to EasyEDA- definitely not a handy thing...

**Comment by piotrva** [comment]
[Schematic_espkey_2021-07-18.pdf](https://github.com/octosavvi/ESPKey/files/6836575/Schematic_espkey_2021-07-18.pdf)

**Comment by Dan-Rdd** [comment]
Im finding it hard to find parts based on the bom

**Comment by aSmig** [comment]
This was clearly an oversight on my part. Sorry for the hassle and thanks for finding your own way in the interim. Added in https://github.com/octosavvi/ESPKey/commit/e7455d395015cc0b97b9b0d487159943da6d5e61
