### ISSUE TITLE
why its telling file not found

### ISSUE THREAD

**Issue by ghost** [octosavvi/ESPKey#10]
![image](https://user-images.githubusercontent.com/101780167/170671477-ee0576cd-e31a-4492-b5d0-7f16945e768d.png)

**Comment by DidierA** [comment]
After the first firmware upload, the filesystem is empty, hence the 'FileNotFound' message. You need to launch the ui-update.sh script. Check 'Updating UI' in [the documentation](https://www.redteamtools.com/content/ESPKey%20Tool%20Manual%20v1.0.0.pdf).
