### ISSUE TITLE
Source for IDC connectors?

### ISSUE THREAD

**Issue by BuckarewBanzai** [octosavvi/ESPKey#2]
Does anyone have a source for the 2 IDC connectors and/or what the suggested wire gauge would be?

"P1, ","1","Power","CONN_2","Connector_IDC_SMD:SSL_DW_IDC_02","",""
"P2, ","1","Wiegand","CONN_3","Connector_IDC_SMD:SSL_DW_IDC_03","",""

**Comment by 0xDezzy** [comment]
You can find the IDC connectors and punch down bit here: https://www.mouser.com/Search/Refine?Ntk=P_MarCom&Ntt=163398077

**Comment by Dan-Rdd** [comment]
> You can find the IDC connectors and punch down bit here: https://www.mouser.com/Search/Refine?Ntk=P_MarCom&Ntt=163398077

thank you

**Comment by aSmig** [comment]
The AVX part numbers 009176002022006 (2-position) and 009176003022006 (3-position) are available through DigiKey, Mouser, Newark, Arrow, etc. These parts are designed for 22 AWG stranded wire but variants are available for 18 AWG through 24 AWG if your target site is using these sizes. 22 AWG seems to be the most common.
