### ISSUE TITLE
ESP8266 - Revision?

### ISSUE THREAD

**Issue by CyberCityCircuits** [octosavvi/ESPKey#4]
Could you tell me what revision of the ESP8266 the retail version of this was built with?  I have the 12-E and 12-F and neither have the external antenna connection.

**Comment by shadeunicorns** [comment]
I ordered a run of 12f versions and they worked fine.
the version shown off on LPL and avalible through Redteamtools uses the esp-07 variant. however i ordered the 12f versions to avoid needing to connect an external u.fl antenna

**Comment by aSmig** [comment]
The retail version includes a custom ESP-07 with increased capacity SPI Flash. The ESP-07 usually has 1 MB flash but ESPKey ships with 4 MB for increased logging capacity. As detailed elsewhere the ESP-07 includes a chip antenna. I've found that the on-board chip antenna performs well for most installations and have only needed to add an external antenna via U.FL when installing the module inside of a fully enclosed metal box. Even in a metal box, short range connections are often possible.
